# -*- coding: utf-8 -*-
"""config.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TTpwbZxrqlQeyZ61J0JqfUrJ8kAQDONP
"""

# police_report_bot/
# |
# ├── groq_api_key.txt
# │
# ├── src/
# |   ├── utils.py
# |   ├── pipeline.py
# │   ├── config.py
# │   ├── data_loader.py
# │   ├── scenario_generator.py
# │   ├── interview_bot.py
# │   ├── grader.py
# │   ├── session_logger.py
# │   ├── ui.py
# │   └── app.py
# │
# ├── source_docs/
# │   ├── checklists/            # original PDFs (already exists)
# │   ├── checklists_json/       # the 6 JSON files (already exists)
# │   ├── manuals/               # reference PDFs (already exists)
# │   └── legal_context/         # legal_context.txt (already exists)
# │
# ├── validation/
# │   └── scenarios_for_review.pdf   # already exists
# │
# └── sessions/                  # new — where completed session logs get saved

import os

# Base directory
BASE_DIR = "/content/drive/MyDrive/police_report_bot-1.0.0-alpha"

# Paths
CHECKLIST_DIR           = f"{BASE_DIR}/source_docs/checklists"
CHECKLIST_JSON_DIR      = f"{BASE_DIR}/source_docs/checklists_json"
MANUALS_DIR             = f"{BASE_DIR}/source_docs/manuals"
LEGAL_CONTEXT_DIR       = f"{BASE_DIR}/source_docs/legal_context"
WRITING_STANDARDS_DIR   = f"{BASE_DIR}/source_docs/writing_standards"
SESSIONS_DIR            = f"{BASE_DIR}/sessions"

os.makedirs(SESSIONS_DIR, exist_ok=True)

# API
with open(f"{BASE_DIR}/groq_api_key.txt") as f:
    GROQ_API_KEY = f.read().strip()

MODEL_NAME = "llama-3.3-70b-versatile"
WEAK_MODEL = "llama-3.1-8b-instant"
# Filter model included in config but not being used as main model worked better
# Filter model is still here just in case it is needed later

# Crime types
CRIME_TYPES = [
    "Domestic Violence",
    "Stalking",
    "Sexual Assault",
    "Partner/Family Member Assault",
    "Protection Order Violation",
    "Strangulation"
]

CHECKLIST_FILES = {
    "Domestic Violence":             "domestic_violence_checklist.pdf",
    "Stalking":                      "stalking_checklist.pdf",
    "Sexual Assault":                "sexual_assault_checklist.pdf",
    "Partner/Family Member Assault": "partner_family_member_assault_checklist.pdf",
    "Protection Order Violation":    "protection_order_violations_checklist.pdf",
    "Strangulation":                 "strangulation_checklist.pdf",
}

CRIME_TYPE_CODES = {
    "Domestic Violence": "dv",
    "Stalking": "s",
    "Sexual Assault": "sa",
    "Partner/Family Member Assault": "pfma",
    "Protection Order Violation": "pov",
    "Strangulation": "st"
}

# Model temperature settings
TEMP_DETERMINISTIC = 0
TEMP_CREATIVE      = 0.7

# Chunking for legal context
CHUNK_SIZE        = 3500
CHUNK_OVERLAP     = 300
MAX_TOKENS_FILTER = 5

NAMES_AND_ADDRESSES = """
Use diverse and varied fictional names and addresses that reflect a variety of ethnicities and backgrounds.
Use realistic but varied street names, numbers, cities, and states.
"""