# -*- coding: utf-8 -*-
"""data_loader.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y1N8pDOK1_pv7orkfB5k66D3B9zIHnUY
"""

import os
import json
from config import CHECKLIST_JSON_DIR, LEGAL_CONTEXT_DIR, WRITING_STANDARDS_DIR

def load_checklist(crime_type):
    slug = crime_type.lower().replace(" ", "_").replace("/", "_")
    filepath = os.path.join(CHECKLIST_JSON_DIR, f"{slug}.json")
    with open(filepath) as f:
        return json.load(f)

def load_legal_context():
    filepath = os.path.join(LEGAL_CONTEXT_DIR, "legal_context.txt")
    with open(filepath) as f:
        return f.read()

def load_writing_standards():
    filepath = os.path.join(WRITING_STANDARDS_DIR, "writing_standards.txt")
    with open(filepath) as f:
        return f.read()